version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      GF_SERVER_HTTP_PORT: $PORT
      GF_SERVER_DOMAIN: "grafana"
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_INSTALL_PLUGINS: "marcusolsson-csv-datasource"
    volumes:
      - grafana-storage:/var/lib/grafana
  server:
    build: .
    ports:
      - 80:80
    environment:
      GRAFANA_HOST: "http://grafana:3000"
      HOST_URL: "http://server"
    depends_on:
      - grafana
volumes:
  grafana-storage: {}
