version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  server:
    build: .
    ports:
      - 80:80
    environment:
      GRAFANA_HOST: "http://grafana:3000"
      HOST_URL: "http://server"
    depends_on:
      - grafana
volumes:
  grafana-storage: {}
